name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: symfonycorp/security-checker-action@v2
      - name: Install composer
        uses: php-actions/composer@v5
      - name: Run tests suite
        uses: php-actions/phpunit@v2